name: Build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install cross-compilation deps
        run: |
          sudo apt update
          sudo apt install -q -y \
            binfmt-support \
            gcc-aarch64-linux-gnu \
            qemu-system-aarch64 \
            qemu-user-static

      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux
            max-jobs = auto
            system-features = big-parallel kvm

      - name: Install Cachix
        uses: cachix/cachix-action@v14
        with:
          name: 3waffel
          authToken: "${{secrets.CACHIX_AUTH_TOKEN}}"

      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build NixOS config
        run: nix build -L --no-link .#packages.aarch64-linux.default
